### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by LtSnuggie** [yz91024/Save-Fred-Game#1]
Hey Lindsay said you thought you had a way to deploy your app. What did you find.

**Comment by yz91024** [comment]
I think I can deploy it using only HTML.

**Comment by LtSnuggie** [comment]
How are you thinking about doing that?

**Comment by LtSnuggie** [comment]
Also, what class is your main function in?

I was trying to wrap your app in a .jnlp file but it looked like Java was having issues finding your main method. I was trying javagame.Game as it appeared main(args) was in there.

**Comment by yz91024** [comment]
The class is javagame.Game.class. It is an applet so it uses init(), start(), and run() instead of main()

**Comment by yz91024** [comment]
I am using the applet tag in HTML to run it.

**Comment by LtSnuggie** [comment]
Have you gotten the applet tag to work? Currently the only supported browsers are IE/Safari according to the Orcale documentation

**Comment by LtSnuggie** [comment]
If you cannot get the applet tag to work you will need to convert it to an application.

See: http://docs.oracle.com/javase/7/docs/technotes/guides/jweb/applet_migration.html

Look at the section titled 'Re-writing a Java Applet as a Java Web Start Application'

**Comment by ghost** [comment]
Steven, which version of Java did you use when you wrote this?

**Comment by yz91024** [comment]
I used 1.8

**Comment by LtSnuggie** [comment]
Steven if you cannot get your applet running in pure HTML that is launched _**outside of the eclipse IDE**_ I will need you to build the game as application as outline in the article I posted above.

If you do get it to launch please add the HTML to your project and commit the files.

**Comment by yz91024** [comment]
Ok

**Comment by LtSnuggie** [comment]
Steven, Ms Walker said you got her a jar. Was this jar built as an application with a main() wrapper around your run() and init() functions to get the game running?

**Comment by yz91024** [comment]
Yes

**Comment by LtSnuggie** [comment]
Perfect, I will try to get this deployable this weekend.
